In [2]:
import numpy as np

In [51]:
#definindo um vetor de 1 dim
lista = [x for x in range(100)]
vetor = np.array(lista)
vetor

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
#definindo um vetor de 2 dim
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz_vetor = np.array(matriz)
matriz_vetor.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#criando um vetor a partir de uma sequência
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#criando um vetor a partir de uma sequência pulando de 3 em 3
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
#cria um vetor de n zeros
np.zeros(4) #n=4

array([0., 0., 0., 0.])

In [14]:
#cria uma matriz de nxm zeros
np.zeros([4,5]) #n=4 m=5


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#cria um vetor de n uns
np.ones(4) #n=4

array([1., 1., 1., 1.])

In [18]:
#cria uma matriz de nxm uns
np.ones((4,5)) #n=4 m=5, pode usar o "[]" também


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#cria uma matriz identidade de ordem n
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
#cria um vartor onde os paramêtros são: o número incial, número final e quantos números estarão na sequência:
np.linspace(3,15,5)

array([ 3.,  6.,  9., 12., 15.])

In [23]:
np.linspace(3,15,2)

array([ 3., 15.])

In [24]:
np.linspace(3,15,12)

array([ 3.        ,  4.09090909,  5.18181818,  6.27272727,  7.36363636,
        8.45454545,  9.54545455, 10.63636364, 11.72727273, 12.81818182,
       13.90909091, 15.        ])

In [26]:
#retorna um vetor de n dimensões com valores aleatorios:
np.random.rand(4)

array([0.86597038, 0.0282838 , 0.80709098, 0.74902042])

In [27]:
np.random.rand(4,3)

array([[0.55974018, 0.67141708, 0.42965597],
       [0.77861249, 0.94076521, 0.40126868],
       [0.32109031, 0.54772934, 0.44020204],
       [0.86009435, 0.44249496, 0.85764898]])

In [28]:
np.random.rand(4,3,2)

array([[[0.23985907, 0.64784137],
        [0.61286216, 0.56876695],
        [0.78961841, 0.20657012]],

       [[0.51346736, 0.11996739],
        [0.19705307, 0.03220489],
        [0.51619793, 0.86356942]],

       [[0.99824631, 0.60033274],
        [0.86124643, 0.12376057],
        [0.45247726, 0.19718239]],

       [[0.3296486 , 0.23964844],
        [0.53429938, 0.637393  ],
        [0.37104318, 0.05848905]]])

In [29]:
np.random.rand(5,4,3,2)

array([[[[0.24502064, 0.06104752],
         [0.68417253, 0.84359161],
         [0.69587146, 0.01744229]],

        [[0.70020292, 0.44903283],
         [0.66548431, 0.15793542],
         [0.39970013, 0.27794759]],

        [[0.15741492, 0.18372949],
         [0.13185334, 0.03613227],
         [0.7101513 , 0.12676494]],

        [[0.94825338, 0.83182379],
         [0.63264424, 0.39104665],
         [0.92787153, 0.4534704 ]]],


       [[[0.42930247, 0.42338712],
         [0.63763398, 0.57547247],
         [0.74008516, 0.6151204 ]],

        [[0.95248094, 0.9278279 ],
         [0.87400138, 0.68456265],
         [0.37656226, 0.73192138]],

        [[0.32165754, 0.11968889],
         [0.6817245 , 0.99025478],
         [0.62496529, 0.69738912]],

        [[0.68530619, 0.99519694],
         [0.9443965 , 0.79810609],
         [0.90209838, 0.469372  ]]],


       [[[0.92601907, 0.72755475],
         [0.09382019, 0.63018293],
         [0.45654235, 0.8763734 ]],

        [[0.32945484, 0.268556  ]

In [33]:
#cria um vetor de inteiros aleatorios (segundo paramêtro não incluso)
np.random.randint(3,30,2)

array([3, 3])

In [34]:
np.random.randint(3,30,20)

array([ 7, 25,  6, 16, 21, 24, 19, 17, 21, 15, 22,  6, 25, 20, 15, 17, 15,
       13, 27,  7])

In [35]:
#transforma vetor em matriz de tamanho k e uma matriz nxm
np.ones(25).reshape(5,5)# k=5, m = n = 5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
#Diz o tamanho
np.ones(25).shape

(25,)

In [39]:
np.ones(25).reshape(5,5).shape

(5, 5)

In [42]:
#acha o valor maximo de um vetor
np.ones(25).reshape(5,5).max()

1.0

In [41]:
#acha o valor minimo de um vetor
np.ones(25).reshape(5,5).min()

1.0

In [43]:
#acha o indice do valor maximo de um vetor (se houver varios, retorna a primeira ocorrência)
np.ones(25).reshape(5,5).argmax()

0

In [44]:
#acha o indice do valor minimo de um vetor (se houver varios, retorna a primeira ocorrência)
np.ones(25).reshape(5,5).argmin()

0

In [46]:
#indexação
#pegando um elemento
vetor[0]

0

In [48]:
#pegando uma sequência de elementos
vetor[0:5]

array([0, 1, 2, 3, 4])

In [49]:
vetor[0:10:2]

array([0, 2, 4, 6, 8])

In [52]:
matriz2 = vetor.reshape(10,10)
matriz2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
#pegando elementos de matrizes
#o primeiro colchetes faz menção a linha e o segundo as colunas
matriz2[1][9]#oega um elemento

19

In [69]:
#pegando uma linha
matriz2[:][2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [70]:
matriz2[2][:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
matriz2[2][:] == matriz2[:][2]#pra evitar esse problema eu uso a notação matriz2[lin,col] ou matriz2[linI:linF,colI:ColF]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [85]:
matriz2[:2,:]

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999]])

In [86]:
matriz2[:,:2]

array([[999, 999],
       [999, 999],
       [999, 999],
       [ 30,  31],
       [ 40,  41],
       [ 50,  51],
       [ 60,  61],
       [ 70,  71],
       [ 80,  81],
       [ 90,  91]])

In [72]:
#é possivel pegar algumas linhas omitindo as colunas
matriz2[2:6]#pega da terceira até a sexta linha (omitindo a setima)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [74]:
#obs: se vc declara um array como um subconjunto de um segundo array e e então altera o primeiro array
#os elementos do segundo array correspondente ao primeiro array também serão alteradas
ex = matriz2[:3]
ex

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [75]:
ex[:] = 999
ex

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999]])

In [77]:
matriz2

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [88]:
#para evitar isso usa-se o .copy ao declarar o ex
ex = matriz2[:3].copy()
ex

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999]])

In [89]:
ex[:] = 0
ex

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [90]:
matriz2

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [91]:
#é possivel criar uma vetor de booleans onde cada elemento do vetor passa por um teste de comparação
#e um valor boolean e atribuido ao seu indice
bol = matriz2 == 999
bol

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [103]:
#operações vetor e escalar
#a operação é repetida entre todos os elementos da matriz e o escalar
matriz3 = np.arange(1,101).reshape(10,10)
matriz3

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [104]:
matriz3+3

array([[  4,   5,   6,   7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33],
       [ 34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62,  63],
       [ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73],
       [ 74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93],
       [ 94,  95,  96,  97,  98,  99, 100, 101, 102, 103]])

In [105]:
matriz3-10

array([[-9, -8, -7, -6, -5, -4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [106]:
10-matriz3

array([[  9,   8,   7,   6,   5,   4,   3,   2,   1,   0],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10],
       [-11, -12, -13, -14, -15, -16, -17, -18, -19, -20],
       [-21, -22, -23, -24, -25, -26, -27, -28, -29, -30],
       [-31, -32, -33, -34, -35, -36, -37, -38, -39, -40],
       [-41, -42, -43, -44, -45, -46, -47, -48, -49, -50],
       [-51, -52, -53, -54, -55, -56, -57, -58, -59, -60],
       [-61, -62, -63, -64, -65, -66, -67, -68, -69, -70],
       [-71, -72, -73, -74, -75, -76, -77, -78, -79, -80],
       [-81, -82, -83, -84, -85, -86, -87, -88, -89, -90]])

In [107]:
matriz3*2

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150, 152, 154, 156, 158, 160],
       [162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198, 200]])

In [108]:
1/matriz3

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.04761905, 0.04545455, 0.04347826, 0.04166667, 0.04      ,
        0.03846154, 0.03703704, 0.03571429, 0.03448276, 0.03333333],
       [0.03225806, 0.03125   , 0.03030303, 0.02941176, 0.02857143,
        0.02777778, 0.02702703, 0.02631579, 0.02564103, 0.025     ],
       [0.02439024, 0.02380952, 0.02325581, 0.02272727, 0.02222222,
        0.02173913, 0.0212766 , 0.02083333, 0.02040816, 0.02      ],
       [0.01960784, 0.01923077, 0.01886792, 0.01851852, 0.01818182,
        0.01785714, 0.01754386, 0.01724138, 0.01694915, 0.01666667],
       [0.01639344, 0.01612903, 0.01587302, 0.015625  , 0.01538462,
        0.01515152, 0.01492537, 0.01470588, 0.01449275, 0.01428571],
       [0.01408451, 0.01388889, 0.0136986

In [109]:
#operações entre matrizes
# a operação acontece entre os elemntos de mesmo indice
matriz3+matriz3

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150, 152, 154, 156, 158, 160],
       [162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198, 200]])

In [110]:
matriz3/matriz3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [111]:
matriz3**matriz3

array([[          1,           4,          27,         256,        3125,
              46656,      823543,    16777216,   387420489,  1410065408],
       [ 1843829075,  -251658240, -1692154371, -1282129920,  1500973039,
                  0,  1681328401,   457441280,  -306639989,           0],
       [  878082373,   977272832, -1276351769,           0,  1296002393,
          603979776,  -714244925,           0, -1266004979,  1073741824],
       [-2010103841,           0,   942687265,           0,   618402555,
                  0,  -200711083,           0,  1583713495,           0],
       [ 2110296937,           0,   407106611,           0, -1714755555,
                  0,  1686099919,           0,    20963633,           0],
       [ -329759125,           0, -1690305179,           0,  2006722247,
                  0,  1071068025,           0,   915746723,           0],
       [ 1062783533,           0,  1526857663,           0,  1526861889,
                  0,   882693595,           0

In [117]:
vetor = np.arange(0,100)
matriz2 = vetor.reshape(10,10)
matriz2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
matriz3/matriz2 #nesse caso o primeiro elemento é 1/0, oque daria um erro normalmente mas nesse caso só aparece
                #um aviso e os demais são executados normalmente

<ipython-input-119-8bea9883fedd>:1: RuntimeWarning: divide by zero encountered in true_divide
  matriz3/matriz2


array([[       inf, 2.        , 1.5       , 1.33333333, 1.25      ,
        1.2       , 1.16666667, 1.14285714, 1.125     , 1.11111111],
       [1.1       , 1.09090909, 1.08333333, 1.07692308, 1.07142857,
        1.06666667, 1.0625    , 1.05882353, 1.05555556, 1.05263158],
       [1.05      , 1.04761905, 1.04545455, 1.04347826, 1.04166667,
        1.04      , 1.03846154, 1.03703704, 1.03571429, 1.03448276],
       [1.03333333, 1.03225806, 1.03125   , 1.03030303, 1.02941176,
        1.02857143, 1.02777778, 1.02702703, 1.02631579, 1.02564103],
       [1.025     , 1.02439024, 1.02380952, 1.02325581, 1.02272727,
        1.02222222, 1.02173913, 1.0212766 , 1.02083333, 1.02040816],
       [1.02      , 1.01960784, 1.01923077, 1.01886792, 1.01851852,
        1.01818182, 1.01785714, 1.01754386, 1.01724138, 1.01694915],
       [1.01666667, 1.01639344, 1.01612903, 1.01587302, 1.015625  ,
        1.01538462, 1.01515152, 1.01492537, 1.01470588, 1.01449275],
       [1.01428571, 1.01408451, 1.0138888

In [120]:
matriz2/matriz3

array([[0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
        0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ],
       [0.90909091, 0.91666667, 0.92307692, 0.92857143, 0.93333333,
        0.9375    , 0.94117647, 0.94444444, 0.94736842, 0.95      ],
       [0.95238095, 0.95454545, 0.95652174, 0.95833333, 0.96      ,
        0.96153846, 0.96296296, 0.96428571, 0.96551724, 0.96666667],
       [0.96774194, 0.96875   , 0.96969697, 0.97058824, 0.97142857,
        0.97222222, 0.97297297, 0.97368421, 0.97435897, 0.975     ],
       [0.97560976, 0.97619048, 0.97674419, 0.97727273, 0.97777778,
        0.97826087, 0.9787234 , 0.97916667, 0.97959184, 0.98      ],
       [0.98039216, 0.98076923, 0.98113208, 0.98148148, 0.98181818,
        0.98214286, 0.98245614, 0.98275862, 0.98305085, 0.98333333],
       [0.98360656, 0.98387097, 0.98412698, 0.984375  , 0.98461538,
        0.98484848, 0.98507463, 0.98529412, 0.98550725, 0.98571429],
       [0.98591549, 0.98611111, 0.9863013

In [121]:
#funções do numpy
np.sin(matriz3)# seno de cada elemento

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
        -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
         0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162],
       [-0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
        -0.99177885, -0.64353813,  0.29636858,  0.96379539,  0.74511316],
       [-0.15862267, -0.91652155, -0.83177474,  0.01770193,  0.85090352,
         0.90178835,  0.12357312, -0.76825466, -0.95375265, -0.26237485],
       [ 0.67022918,  0.98662759,  0.39592515, -0.55878905, -0.99975517,
        -0.521551  ,  0.43616476,  0.99287265,  0.63673801, -0.30481062],
       [-0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,  0.82682868,
        -0.02655115, -0.85551998, -0.89792768

In [122]:
np.sqrt(matriz3)# raiz quadrada de cada elemento

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
         2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766],
       [ 3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
         4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595],
       [ 4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
         5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558],
       [ 5.56776436,  5.65685425,  5.74456265,  5.83095189,  5.91607978,
         6.        ,  6.08276253,  6.164414  ,  6.244998  ,  6.32455532],
       [ 6.40312424,  6.4807407 ,  6.55743852,  6.63324958,  6.70820393,
         6.78232998,  6.8556546 ,  6.92820323,  7.        ,  7.07106781],
       [ 7.14142843,  7.21110255,  7.28010989,  7.34846923,  7.41619849,
         7.48331477,  7.54983444,  7.61577311,  7.68114575,  7.74596669],
       [ 7.81024968,  7.87400787,  7.93725393,  8.        ,  8.06225775,
         8.1240384 ,  8.18535277,  8.24621125

In [123]:
np.mean(matriz3)# media da matriz

50.5

In [124]:
np.std(matriz3)# desvio padrão da matriz

28.86607004772212