In [2]:
import numpy as np

In [16]:
#criando array unidimensional
lista = [1,2,3]
vetor = np.array(lista)
vetor

array([1, 2, 3])

In [7]:
#cada array tem uma forma ,dtype e numero de dimensões
vetor.shape  #

(3,)

In [15]:
vetor.dtype
#int32 quer dizer inteiro de 32 bits

dtype('int32')

In [17]:
vetor.ndim

1

In [18]:
#criando array bidimensional
lista = [[1,2,3],[4,5,6]]
vetor = np.array(lista)
vetor

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
vetor.shape

(2, 3)

In [20]:
vetor.ndim

2

In [22]:
np.empty((3,6)) # cria um array com  a forma da tupla passada (ou número se o array for 1dim) com 0 ou números aleatórios

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.12199579e-314,             nan, 0.00000000e+000]])

In [24]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.asarray(lista)
#Converte a entrada para um ndarray, mas não copia se a entrada já for um ndarray


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
lista # não muda a lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
# convertendo tipos
vetor2 = vetor.astype(np.int64)

In [33]:
vetor2
#se converter de flutuante para decimal, a parte decimal será truncada

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [34]:
#é possivel também definir o dtype na criação do array
lista = [[1,2,3],[4,5,6]]
vetor = np.array(lista, np.float64)
vetor

array([[1., 2., 3.],
       [4., 5., 6.]])